### PR TITLE
Upgrade to NET 6.0

### LINKED ISSUE #144: [Feature] Support .NET 6
After upgrading to Visual Studio 2022 and .net 6, `dotnet-octo` is no longer working for me. I'm getting the error:
```
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '5.0.0' (x64) was not found.
  - The following frameworks were found:
      3.1.21 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      6.0.0 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=5.0.0&arch=x64&rid=win10-x64
```

I thought that #50 would allow backwards compatibility with .net core 3.1 LTS, but I'm not having very good luck with that.

I installed the latest version of the tool today:
```
> dotnet tool install Octopus.DotNet.Cli --global
You can invoke the tool using the following command: dotnet-octo
Tool 'octopus.dotnet.cli' (version '3451.0.3458') was successfully installed.

> dotnet tool list --global
Package Id              Version          Commands
----------------------------------------------------
octopus.dotnet.cli      3451.0.3458      dotnet-octo
```

### PR DESCRIPTION
**Pull request by mtrutledge**
Upgrades the Nuke.Build version to 6.0.1 and upgrades the .NET version to include net6.0

Fixes #144

### CODE REVIEW

**Comment by johnsimons** [comment]
@slewis74 should we also update the docker images to run against net6 runtime?
https://github.com/OctopusDeploy/OctopusCLI/blob/master/Dockerfiles/alpine/Dockerfile
https://github.com/OctopusDeploy/OctopusCLI/blob/master/Dockerfiles/nanoserver/Dockerfile

**Comment by mtrutledge** [comment]
I have updated the docker files to reference new runtimes

**Comment by johnsimons** [comment]
@mtrutledge we still figuring out what else we want to be upgraded to `net6`, so I am sorry we have been a bit slow on this one.

I was thinking that it makes sense to also upgrade all the projects to `net6`. So just to be clear we can upgrade the following:
image

I hope this makes sense?
BTW, is there a way for me to contribute to this PR?

**Comment by mtrutledge** [comment]
@johnsimons I do have the Allow Edits by Maintainers option checked, so you should be able to contribute to the PR. If not I can go into each of the csproj files and update them to net6.0

**Comment by mtrutledge** [comment]
How is this review going?

**Comment by johnsimons** [comment]
@mtrutledge this is pretty much ready to go, but unfortunately is blocked by our TeamCity infrastructure not supporting `net6` yet, so we need to wait a bit to get that sorted first. I hope this makes sense.

**Review by johnsimons — APPROVED** [review]

**Comment by mtrutledge** [comment]
@johnsimons Awesome. Thanks for the update.

**Comment by mtrutledge** [comment]
@johnsimons Just checking in to see how upgrading the TeamCity build environment to NET 6 is going?

**Comment by johnsimons** [comment]
@mtrutledge we haven't forgotten this one.
Everything is progressing, we've decided that we actually want to move to Github Actions, and on top of that we are also removing EOL frameworks, I have done a [spike](https://github.com/OctopusDeploy/OctopusCLI/pull/154) on both of these. 
Where we are at the moment is coordinating the plan to remove EOL Frameworks.

Sorry for dragging this one, are you waiting on something in particular?

**Comment by mtrutledge** [comment]
I have a project that builds in azure pipelines in net6 however the octopus packaging tasks fail because the azure instance can’t find net 5 to run the tools. When attempting to add net 5 and 6 to the azure pipeline the build fails. That prompted me to do the pull request to update the tools to net 6

**Comment by daniel-shane-orbis** [comment]
We're actually also blocked for a very similar reason - our build images only have .net 6 on them, so our migrated builds work right up to the octo cli commands in our docker files, but then fail because of the lack of net 5. With this change, it ought to completely unblock our .net 6 migration.

**Comment by johnsimons** [comment]
@mtrutledge I am trying to understand more about your requirement, you mention the usage of the pack command, I assume you referring to https://octopus.com/docs/octopus-rest-api/octopus-cli/pack ?
I am asking because we are actually considering removing this command, and instead, just suggest using `zip` or `nuget` or `dotnet pack`, any thoughts on this?

**Comment by johnsimons** [comment]
@daniel-shane-orbis also trying to understand your usage, so you need to run OctopusCLI in a host that only has net6 installed?
Have you considered using our [docker container](https://octopus.com/downloads/octopuscli#docker) instead? Or the [self-contained packages](https://octopus.com/downloads/octopuscli#linux)?
image

**Comment by daniel-shane-orbis** [comment]
> @daniel-shane-orbis also trying to understand your usage, so you need to run OctopusCLI in a host that only has net6 installed? Have you considered using our [docker container](https://octopus.com/downloads/octopuscli#docker) instead? Or the [self-contained packages](https://octopus.com/downloads/octopuscli#linux)?

In all honesty, I hadn't realised the containerised version existed - I'll imagine we'll be able to make something work with it though, so thanks for highlighting!

On the `dotnet octo pack` command, we actually find it really useful because it makes it much easier for us to deal with transitive dependencies (where `dotnet pack` can be annoying for our use case). But we could probably achieve the same thing with nuget / zipping directly - it'd just take a bit of reworking.

**Comment by mtrutledge** [comment]
@johnsimons I really enjoy the `dotnet octo pack` command just as @daniel-shane-orbis does. It makes packaging quick and straightforward without the need to fiddle with nuspec files or other configurations. This probably is not the thread to have a conversation about the plans for removing this feature, but I like this feature quite a bit. If it is removed, have you considered other tools to make user transitions from `dotnet octo pack` to `dotnet pack` just as easy?  I also assume in my azure pipelines situation that my `dotnet octo deploy-release` and `create-release` command would fail for the same reasons. I am aware there are specific Octopus Deploy extensions in azure, however we use NUKE Build to ensure the build runs the same in pipelines as well as any other machine, so we are utilizing the octopus cli.

**Pull request merged**
